### PR TITLE
We can now login and logout

### PR DESCRIPTION
**Pull request by dealie16**

### CODE REVIEW

**Comment by ajm188** [comment]
:+1: brilliant. except you didn't run the tests

**Comment by ajm188** [comment]
Also aren't you glad the API is always working the first time

**Comment by ajm188** [comment]
you spelled whiny wrong

**Comment by ajm188** [comment]
winnie the :hankey:

**Comment by ajm188** [comment]
:shipit:

**Comment by ajm188** [comment]
we both know you ammended that message and force pushed...

**Comment by dealie16** [comment]
You don't know me!

**Comment by ajm188** [comment]
[You don't know me at all!](https://www.youtube.com/watch?v=UskSU5BoyZs)

**Pull request merged**
